---

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - erlang
    - elixir
    - golang
    - node
    - docker
    - oh-my-zsh
    - jvm
    - hadoop
    - base
    - common
    - scmbreeze
