---
- name: Create development directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ dev_directories }}"
  tags:
    - dev-setup
    - directories

- name: Create GitHub directory
  file:
    path: "{{ home_dir }}/github"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - github

- name: Create projects directory
  file:
    path: "{{ home_dir }}/projects"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - projects

- name: Create workspace directory
  file:
    path: "{{ home_dir }}/workspace"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - workspace

- name: Create development tools directory
  file:
    path: "{{ home_dir }}/dev-tools"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - tools

- name: Create scripts directory
  file:
    path: "{{ home_dir }}/scripts"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - scripts

- name: Create config directory
  file:
    path: "{{ home_dir }}/.config"
    state: directory
    mode: '0755'
  tags:
    - dev-setup
    - config

- name: Create development aliases
  template:
    src: dev-aliases.sh.j2
    dest: "{{ home_dir }}/.dev-aliases.sh"
    mode: '0644'
  tags:
    - dev-setup
    - aliases

- name: Add development aliases to .zshrc
  lineinfile:
    path: "{{ home_dir }}/.zshrc"
    line: 'source ~/.dev-aliases.sh'
    insertafter: '^# Set personal aliases'
    state: present
  tags:
    - dev-setup
    - aliases

- name: Create development environment file
  template:
    src: dev-env.sh.j2
    dest: "{{ home_dir }}/.dev-env.sh"
    mode: '0644'
  tags:
    - dev-setup
    - env

- name: Add development environment to .zshrc
  lineinfile:
    path: "{{ home_dir }}/.zshrc"
    line: 'source ~/.dev-env.sh'
    insertafter: '^# Set personal aliases'
    state: present
  tags:
    - dev-setup
    - env

- name: Create git configuration
  template:
    src: gitconfig.j2
    dest: "{{ home_dir }}/.gitconfig"
    mode: '0644'
  tags:
    - dev-setup
    - git

- name: Create development tools configuration
  template:
    src: dev-tools-config.sh.j2
    dest: "{{ home_dir }}/.dev-tools-config.sh"
    mode: '0644'
  tags:
    - dev-setup
    - tools-config

- name: Add development tools config to .zshrc
  lineinfile:
    path: "{{ home_dir }}/.zshrc"
    line: 'source ~/.dev-tools-config.sh'
    insertafter: '^# Set personal aliases'
    state: present
  tags:
    - dev-setup
    - tools-config

- name: Create development workspace setup script
  template:
    src: setup-workspace.sh.j2
    dest: "{{ home_dir }}/scripts/setup-workspace.sh"
    mode: '0755'
  tags:
    - dev-setup
    - scripts

- name: Create project template script
  template:
    src: create-project.sh.j2
    dest: "{{ home_dir }}/scripts/create-project.sh"
    mode: '0755'
  tags:
    - dev-setup
    - scripts
