---

- name: Update homebrew
  command: "brew update"
  tags:
    - base
    - brew
    - brew-cask
    - update

- name: Install base homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ brew_base_packages }}"
  tags:
    - base
    - brew

- name: Install brew cask applications
  command: "brew cask install {{item.install_options | default('') }} {{ item.name }}"
  # TODO: Figure out "Error no cask hydra" issue
  # homebrew_cask:
  #   name: "{{ item.name }}"
  #   state: "{{ item.state | default('present') }}"
  #   install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ brew_cask_applications }}"
  ignore_errors: True
  tags:
    - base
    - brew
    - brew-cask

- name: Install brew taps
  homebrew_tap:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ brew_taps }}"
  tags:
    - base
    - brew
    - brew-tap

- name: Cleanup homebrew
  command: "brew cleanup -s"
  ignore_errors: True
  tags:
    - base
    - brew
    - cleanup

- name: Cleanup cask
  command: "brew cask cleanup"
  ignore_errors: True
  tags:
    - base
    - brew
    - brew-cask
    - cleanup

- name: Link homebrew apps
  command: "brew linkapps"
  tags:
    - base
    - brew
    - brew-cask

- name: ssh dir
  file:
    path: "{{ home_dir }}/.ssh"
    state: directory
  tags:
    - base

- name: Project workspace
  file:
    path: "{{ workspace_dir }}"
    state: directory
  tags:
    - base

- name: User tmp dir
  file:
    path: "{{ home_dir }}/tmp"
    state: directory
  tags:
    - base
